name: Run Pester Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: actions/setup-powershell@v3

    - name: Read properties file and set environment variables
      shell: pwsh
      run: |
        # Read the properties file and set environment variables
        $properties = Get-Content -Path "test.properties" | ConvertFrom-StringData
        foreach ($key in $properties.Keys) {
          $value = $properties[$key]
          Write-Output "Setting environment variable: $key=$value"
          [Environment]::SetEnvironmentVariable($key, $value, "Process")
        }

    - name: Run Pester tests
      shell: pwsh
      run: |
        Invoke-Pester -Path ./tests.ps1 -Output Detailed
