name: Run Pester Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load Environment Variables from File
        run: |
          # Assuming you have a file called 'env_variables.txt'
          Get-Content './test.properties' | ForEach-Object {
            $split = $_.Split('=')
            if ($split.Length -eq 2) {
              # Write the variable to the GITHUB_ENV file
              echo "$($split[0])=$($split[1])" >> $env:GITHUB_ENV
            }
          }

      - name: Install Pester
        run: Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run Pester Tests
        run: |
          # Now you can access the environment variables in your Pester test cases
          Invoke-Pester -Script ./tests.ps1
